### ISSUE TITLE
Create a CHANGELOG.md. SemVer. CONTRIBUTING.md

### ISSUE THREAD

**Issue by rylanb** [boulder-food-rescue/food-rescue-robot#48]
We need to standardize versioning / contributing / change log.

**Comment by rylanb** [comment]
https://github.com/bjankord/Style-Guide-Boilerplate/blob/master/CONTRIBUTING.md

and

https://github.com/bjankord/Style-Guide-Boilerplate/blob/master/CHANGELOG.md

Also could stand to review PR template.

**Comment by bkuhlmann** [comment]
Yeah, this would be most helpful. Would you want to use a format like this? Examples:

- [CONTRIBUTING](https://github.com/bkuhlmann/dotfiles/blob/master/CONTRIBUTING.md) (granted, you don't have to include the links to my styles guides...but there might be some good stuff to pull from there though).
- [CHANGES](https://github.com/bkuhlmann/dotfiles/blob/master/CHANGES.md) - Whether you call it CHANGES or CHANGELOG is fine by me. The important part is adding a date/time stamp with each release tag. I use a gem called [Milestoner](https://github.com/bkuhlmann/milestoner) to automate the construction of the changes/history (which also gets bundled up in the Git Tag for the project -- this is nice because we can bake our releases in to Git tags for posterity).

Food for thought...if you need more examples of how the project changes/history could be automated, let me know (although this [screencast](https://asciinema.org/a/91752) might be of interest).

**Comment by rylanb** [comment]
@bkuhlmann Perhaps ya. Those have some nice points / contributing style guides.

For 'Contributing'
I also like -> https://github.com/bbatsov/ruby-style-guide#naming and https://github.com/bbatsov/rails-style-guide as they seem to have a semblance of canonical reference to them. 

You Changes file is perfect.

**Comment by bkuhlmann** [comment]
Yeah, the Rubocop style guide is a good starting point. In order to help enforce that, we'd need to add Rubocop and I'd suggest [Reek](https://github.com/troessner/reek) support too. This won't be any easy task to fix I'm afraid (in terms of retrofitting the older code -- most can be automated but some will require manual tweaking). At least with Rubocop/Reek, new code can be checked as part of the build process so that we don't waiver from our style guide.

I suppose I could open a PR with Rubocop support for review? Both Rubocop and Reek allow for TODOs to generated so current work isn't blocked. I could also add support for `CHANGES.md` too.

**Comment by ericfreese** [comment]
#85 adds rubocop support and cleans up some code.

**Comment by rylanb** [comment]
👍
